name: Update Publications from Google Scholar

on:
  # Run on the 1st of every month at 3 AM UTC
  schedule:
    - cron: '0 3 1 * *'

  # Allow manual trigger from GitHub Actions tab
  workflow_dispatch:

  # Optional: Run on push to main/master for testing
  # push:
  #   branches: [ master ]

jobs:
  update-publications:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Fetch publications from Google Scholar
      run: |
        python fetch_publications.py

    - name: Check for changes
      id: check_changes
      run: |
        if git diff --quiet index.md; then
          echo "changes=false" >> $GITHUB_OUTPUT
          echo "No changes detected in publications"
        else
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "Publications have been updated"
        fi

    - name: Commit and push if changes
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add index.md
        git commit -m "Auto-update publications from Google Scholar

        Generated with Claude Code
        Co-Authored-By: Claude <noreply@anthropic.com>"
        git push

    - name: No changes message
      if: steps.check_changes.outputs.changes == 'false'
      run: |
        echo "✓ Publications are already up to date"
